### ISSUE TITLE
ERROR : In train_model of the road following 

### ISSUE THREAD

**Issue by Pranav-India** [NVIDIA-AI-IOT/jetbot#427]
Hello I have collected the data using the data collection code and now I am trying to train the model on collected data. I am getting following error in doing so..

---------------------------------------------------------------------------
`OSError                                   Traceback (most recent call last)`
`<ipython-input-9-38e8b3503363> in <module>`
`     10     model.train()`
`     11     train_loss = 0.0`
`---> 12     for images, labels in train_loader:`
`     13         images = images.to(device)`
`     14         labels = labels.to(device)`

`/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in __next__(self)`
`    817             else:`
`    818                 del self._task_info[idx]`
`--> 819                 return self._process_data(data)`
`    820 `
`    821     next = __next__  # Python 2 compatibility`

`/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in _process_data(self, data)`
`    844         self._try_put_index()`
`    845         if isinstance(data, ExceptionWrapper):`
`--> 846             data.reraise()`
`    847         return data`
`    848 `

`/usr/local/lib/python3.6/dist-packages/torch/_utils.py in reraise(self)`
`    383             # (https://bugs.python.org/issue2651), so we work around it.`
`    384             msg = KeyErrorMessage(msg)`
`--> 385         raise self.exc_type(msg)`

`OSError: Caught OSError in DataLoader worker process 0.`
`Original Traceback (most recent call last):`
` File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop`
`    data = fetcher.fetch(index)`
`  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch`
`    data = [self.dataset[idx] for idx in possibly_batched_index]`
`  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>`
`    data = [self.dataset[idx] for idx in possibly_batched_index]`
`  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataset.py", line 257, in __getitem__`
`    return self.dataset[self.indices[idx]]`
`  File "<ipython-input-3-3df4b79a2136>", line 23, in __getitem__`
`    image = PIL.Image.open(image_path)`
`  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2590, in open`
`    % (filename if filename else fp))`
`OSError: cannot identify image file 'dataset_xy/xy_140_125_cdde6f46-a024-11eb-9caa-00044be7083b.jpg'`

any help will be appreciated Thank you..

**Comment by Pranav-India** [comment]
The reason for the error was an image was corrupt  after removing the code starts working..
