### ISSUE TITLE
How to import  jetbot modules into my own python project, if I don’t use jupyter.

### ISSUE THREAD

**Issue by 007hjm** [NVIDIA-AI-IOT/jetbot#501]
On the jupyter platform, it can be executed. And I want to use these modules in my python project. 
The version of jetpack is 4.4.1 
Any suggestions? Grateful. 

When i execute 'impot jetbot' :

` import jetbot`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/jetbot-0.4.1-py3.6.egg/jetbot/__init__.py", line 6, in <module>
    from .object_detection import ObjectDetector
  File "/usr/local/lib/python3.6/dist-packages/jetbot-0.4.1-py3.6.egg/jetbot/object_detection.py", line 3, in <module>
    from .tensorrt_model import TRTModel
  File "/usr/local/lib/python3.6/dist-packages/jetbot-0.4.1-py3.6.egg/jetbot/tensorrt_model.py", line 1, in <module>
    import torch
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 196, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 149, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.6/dist-packages/torch/lib/libgomp-d22c30c5.so.1: cannot allocate memory in static TLS block
```

**Comment by 007hjm** [comment]
I commented out 

> from .object_detection import ObjectDetector

 in jetbot.__init__.py (since I did not install the relevant model)


 re-run 

> python3 setup.py install 

And it works.
